platform :ios, '7.0'
target 'iwen' do
pod 'AFNetworking', '~> 2.5.4'
pod 'MJRefresh', '~> 2.4.7'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'JSONModel', '~> 1.0.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'IQKeyboardManager'
pod 'AMapLocation'
pod 'AMap2DMap', '~> 2.5.0'
pod 'HMSegmentedControl@kennygunie', '~> 1.4.2'
pod 'DTCoreText', '~> 1.6.17'
pod 'UMengUShare/UI'

# 集成微信(精简版0.2M)
pod 'UMengUShare/Social/ReducedWeChat'

# 集成微信(完整版14.4M)
pod 'UMengUShare/Social/WeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMengUShare/Social/ReducedQQ'

# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMengUShare/Social/QQ'

# 集成新浪微博(精简版1M)
pod 'UMengUShare/Social/ReducedSina'
end
